CC = gcc

all:
	$(CC) mtodolist.c todolist.c ../daftarpesanan/daftarpesanan.c ../queue/queue.c ../linkedlist/linkedlist.c ../linkedlist/node.c ../location/location.c ../pesanan/pesanan.c ../point/point.c -o minprogresslist