CC = gcc

all:
	$(CC) mgadget.c gadget.c ../bag/bag.c ../daftarpesanan/daftarpesanan.c ../inprogresslist/inprogresslist.c ../listdinloc/listdinloc.c ../listpos/listpos.c ../location/location.c ../map/map.c ../pesanan/pesanan.c ../todolist/todolist.c ../point/point.c ../linkedlist/linkedlist.c ../linkedlist/node.c ../queue/queue.c ../wordmachine/wordmachine.c ../charmachine/charmachine.c ../pcolor/pcolor.c ../matrix/matrix.c -o mgadget