CC = gcc

all:
	$(CC) bag//bag.c charmachine//charmachine.c commands//commands.c config//config.c daftarpesanan//daftarpesanan.c gadget//gadget.c inprogresslist//inprogresslist.c linkedlist//linkedlist.c listdinloc//listdinloc.c listpos//listpos.c location//location.c map//map.c matrix//matrix.c node//node.c pcolor//pcolor.c pesanan//pesanan.c point//point.c queue//queue.c time//time.c todolist//todolist.c wordmachine//wordmachine.c main.c -o main